name: Nightly Feature Suggestions
on:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: write
  issues: write

jobs:
  suggest-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Suggest new improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python .github/scripts/suggest_features.py
