# Configuration for SevenToDie autonomous repository

# New issue welcome message
newIssueWelcomeComment: >
  Thank you for opening this issue! Our autonomous AI system will analyze it shortly.
  
  You can interact with the system using these commands:
  - `/ai fix` - Request the AI to fix this bug automatically
  - `/ai implement` - Request the AI to implement this feature
  - `/ai analyze` - Request detailed analysis of the issue
  - `/ai status` - Check status of AI handling
  - `/ai help` - See all available commands

# New PR welcome message  
newPRWelcomeComment: >
  Thank you for submitting this pull request! Our AI system will review your code.
  
  The review process includes:
  - Code style and quality checks
  - Test coverage analysis
  - Compatibility verification
  
  You'll receive feedback shortly. If you have any questions, just ask in a comment!

# Configuration for PR and Issue labels
labels:
  - name: ai-fix
    color: '5319e7'
    description: 'This issue will be fixed by the AI'
  
  - name: ai-implement
    color: '5319e7'
    description: 'This feature will be implemented by the AI'
    
  - name: attention-needed
    color: 'b60205'
    description: 'Requires immediate human attention'
  
  - name: automated
    color: '0e8a16'
    description: 'Generated by autonomous system'