###################################################
#               SevenToDie Config                 #
###################################################

# Plugin behavior settings
plugin:
  debug: false
  metrics: true
  auto-update: true

# World generation settings
world-generation:
  enabled: true
  
  # Road generation
  roads:
    enabled: true
    width: 3
    material: GRAVEL
    spacing: 256
    chance: 0.75
    
  # Structure generation
  structures:
    enabled: true
    min-distance: 64
    max-distance: 256
    
    # Structure chances (out of 100)
    chances:
      poi_house: 30
      poi_store: 15
      poi_factory: 10
      poi_hospital: 5
      poi_police: 5
      trader_outpost: 5

# Game mechanics
mechanics:
  # Day/night cycle
  day-night:
    blood-moon-interval: 7
    blood-moon-warning-time: 10 # minutes
    blood-moon-zombie-multiplier: 3
    
  # Zombie hordes
  zombie-hordes:
    enabled: true
    min-size: 5
    max-size: 20
    spawn-distance: 50
    despawn-distance: 100
    
  # Building
  building:
    frame-block-durability:
      WOOD: 100
      COBBLE: 250
      REBAR: 500
      CONCRETE: 1000
    
    frame-block-upgrade-requirements:
      WOOD_TO_COBBLE: 5
      COBBLE_TO_REBAR: 10
      REBAR_TO_CONCRETE: 15
      
  # Tools
  tools:
    damage-multipliers:
      pickaxe: 1.5
      axe: 1.2
      shovel: 1.0
      
  # Traders
  traders:
    restock-time: 24 # hours
    open-time: 6 # hour of day
    close-time: 22 # hour of day
    
  # Quests
  quests:
    max-active-per-player: 5
    reward-multiplier: 1.0
    
# Database settings
database:
  type: sqlite # sqlite or mysql
  # Only used for MySQL
  host: localhost
  port: 3306
  database: seventodie
  username: root
  password: password
  
# Advanced settings
advanced:
  custom-zombie-ai: true
  threading:
    max-threads: 4
    thread-priority: 5
  resource-pack:
    enabled: false
    url: ''
    hash: ''