name: SevenToDie
version: '1.0.0'
main: com.seventodie.SevenToDiePlugin
api-version: '1.21'
author: MC7DTD
description: Recreates 7 Days to Die gameplay mechanics in Minecraft
website: https://github.com/mc7dtd/seventodie
softdepend: [WorldEdit, Citizens, ProtocolLib]

permissions:
  seventodie.admin:
    description: Allows access to all SevenToDie commands
    default: op
  seventodie.trader:
    description: Allows access to trader commands
    default: op
  seventodie.quest:
    description: Allows access to quest commands
    default: op
  seventodie.frame:
    description: Allows access to frame block commands
    default: op

commands:
  seventodie:
    description: Main command for the SevenToDie plugin
    usage: |
      /seventodie info - Show plugin information
      /seventodie reload - Reload the plugin
      /seventodie trader [...] - Access trader commands
      /seventodie quest [...] - Access quest commands
      /seventodie reset - Reset plugin data (dangerous)
    aliases: [7td, std]
    permission: seventodie.admin
    
  trader:
    description: Manage traders
    usage: |
      /trader list - List all traders
      /trader spawn - Spawn a trader at your location
      /trader remove <id> - Remove a trader
    permission: seventodie.trader
    
  quest:
    description: Manage quests
    usage: |
      /quest list [active] - List all quests or your active quests
      /quest create <type> <target> <title> - Create a new quest
      /quest complete <id> - Mark a quest as completed
      /quest reset <id> - Reset a quest
      /quest info <id> - Show information about a quest
    permission: seventodie.quest
    
  frame:
    description: Manage frame blocks
    usage: |
      /frame give <type> [amount] - Give frame blocks
      /frame list - List all frame block types
      /frame info - Show information about the frame block you're holding
    permission: seventodie.frame