name: Development Environment

on:
  workflow_dispatch:
    inputs:
      session_duration:
        description: 'Development session duration in minutes'
        required: true
        default: '120'
        type: choice
        options:
          - '60'
          - '120'
          - '180'
          - '240'
      enable_server:
        description: 'Start Paper server'
        required: true
        default: true
        type: boolean

jobs:
  development:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ github.event.inputs.session_duration }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Install Tmate for SSH access
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
      
    - name: Setup Paper server
      if: ${{ github.event.inputs.enable_server == 'true' }}
      run: |
        mkdir -p server
        cd server
        wget -O paper.jar https://api.papermc.io/v2/projects/paper/versions/1.21.4/builds/228/downloads/paper-1.21.4-228.jar
        echo "eula=true" > eula.txt
        mkdir -p plugins
        
    - name: Setup development environment
      run: |
        # Install common development tools
        sudo apt-get update
        sudo apt-get install -y nano vim htop screen tmux
        
        # Create helper scripts
        echo '#!/bin/bash' > build.sh
        echo 'mvn package' >> build.sh
        echo 'cp target/SevenToDie-*.jar server/plugins/' >> build.sh
        chmod +x build.sh
        
        echo '#!/bin/bash' > server.sh
        echo 'cd server' >> server.sh
        echo 'java -Xms1G -Xmx1G -jar paper.jar nogui' >> server.sh
        chmod +x server.sh
        
        echo "======================================"
        echo "Development environment is ready!"
        echo "Use './build.sh' to build the plugin"
        echo "Use './server.sh' to start the server"
        echo "This session will remain active for ${{ github.event.inputs.session_duration }} minutes"
        echo "======================================"
        
    - name: Start Paper Server in background (if enabled)
      if: ${{ github.event.inputs.enable_server == 'true' }}
      run: |
        screen -dmS minecraft ./server.sh
        echo "Server started in screen session. Connect with: screen -r minecraft"
        
    - name: Keep session alive
      run: |
        # This keeps the workflow running for the selected duration
        sleep $((${{ github.event.inputs.session_duration }} * 60 - 300))
        echo "Session will end in 5 minutes"
        sleep 300