name: 🔁 AI Auto-Improvement PR Generator

on:
  # Run on a schedule (every 6 hours)
  schedule:
    - cron: '0 */6 * * *'
  
  # Run when issues are labeled with 'ai-fix'
  issues:
    types: [labeled]
  
  # Allow manual triggers
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to fix (leave empty to process all issues with ai-fix label)'
        required: false

jobs:
  improvement:
    # Only run when an issue is labeled with 'ai-fix' or manually triggered
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'ai-fix')) ||
      github.event_name == 'schedule'
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # We need the full history for branching
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests gitpython
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Process issues with AI implementation
        run: |
          python .github/scripts/ai_implementation.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number || github.event.issue.number || '' }}
