name: AI Plugin Self Test

on:
  push:
    paths:
      - 'plugin/**'
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  self_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile plugin & run tests
        run: echo "Running Minecraft plugin tests and diagnostics"