name: 🧪 AI Self-Test & Auto-Fix

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  selftest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint mypy openai

      - name: Run Self-Test and Diagnostics
        run: |
          python .github/scripts/self_test_and_fix.py

      - name: Upload Diagnostics Log (safe fallback enabled)
        if: always()
        continue-on-error: true
        with:
          name: ai-diagnostics-log
          path: ai_diagnostics.log