name: Auto Merge Dependabot & Autofix PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  checks: read

jobs:
  automerge:
    if: >
      github.actor == 'dependabot[bot]' ||
      startsWith(github.head_ref, 'autofix/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pascalgn/automerge-action@v0.16.1
        with:
          merge-method: squash
          commit-message: merge