name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  issues: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install --upgrade -r requirements.txt black flake8 bandit
          else
            pip install black flake8 bandit
          fi
      - run: black --check .
      - run: flake8 .
      - run: bandit -r .

  build-and-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-cache-${{ hashFiles('**/pom.xml') }}
      - run: mvn --batch-mode verify
      - uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports

  coverage:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install codecov
          codecov

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy here"
