name: Issue on CI Failure
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

permissions:
  issues: write
  checks: read

jobs:
  create-issue-on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create issue on failure
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = context.payload.workflow_run;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `CI failed on ${run.head_branch}`,
              body: `The CI pipeline failed on branch ${run.head_branch}. [View Logs](${run.html_url})`
            });
