name: Lint, Auto-Fix, and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  autofix_lint_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Add ESLint and Prettier
        run: |
          npm install --save-dev eslint prettier
          echo "{}" > .prettierrc.json

      - name: Lint and auto-fix template literal issues
        run: |
          find ./src -type f \( -name "*.ts" -o -name "*.tsx" \) -exec sed -i 's/\" \+ (process.env./\${process.env./g' {} +
          find ./src -type f \( -name "*.ts" -o -name "*.tsx" \) -exec sed -i 's/headers: { Authorization:.*}/headers: { Authorization: `Bearer \${process.env.GITHUB_TOKEN || ""}` }/g' {} +

      - name: Format with Prettier
        run: npx prettier --write .

      - name: Type Check & Build
        run: npm run build
