name: AI Retrospective Review
on:
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  retrospective:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Retrospective AI
        run: |
          pip install openai
          python scripts/ai_engine.py
