name: 🔄 Self-Test and Fix

on:
  # Run daily at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  
  # Run on push to main branch
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'dashboard/**'
  
  # Allow manual triggers
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai requests
      
      - name: Test and fix
        run: |
          python .github/scripts/self_test_and_fix.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      
      - name: Update dashboard data
        run: |
          if [ -d "dashboard/src/data" ]; then
            git config --global user.name "GitHub Actions Bot"
            git config --global user.email "actions@github.com"
            git add dashboard/src/data/*.json
            (git commit -m "Update dashboard data [skip ci]" && git push) || echo "No dashboard changes to commit"
          fi