
name: Talisman Secret Scanner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  talisman-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Talisman
        run: |
          curl https://thoughtworks.github.io/talisman/install.sh | bash
          sudo mv talisman_linux_amd64 /usr/local/bin/talisman

      - name: Run Talisman
        run: talisman --scan
